// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/// @title EVMSTARKVerifier
/// @notice Verifies aggregated Circle STARK proofs on Ethereum L1 using BN254 pairing
/// @dev Generated by EVMetal recursive aggregation system
///
/// Proof pipeline:
///   EVM Transaction → Circle STARK (M31) → Nova IVC → CycleFold → BN254
///
/// Verification cost:
///   - Pairing check: ~300k gas (4 pairings)
///   - Public input validation: ~50k gas
///   - Total: ~350k gas
///
/// Security:
///   - Transparent proving (no trusted setup)
///   - Nova/HyperNova folding provides incrementally verifiable computation
///   - CycleFold defers EC operations to Grumpkin, reducing circuit size
///   - Final BN254 pairing provides O(1) verification
///
/// Reference:
///   - "Nova: Recursive Zero-Knowledge Arguments" (Kothapalli et al. 2022)
///   - "HyperNova: Recursive arguments from folding schemes" (Kothapalli, Setty 2023)
///   - "CycleFold: Folding-scheme-based recursive arguments" (2023)
///   - Circle STARK (StarkWare 2024)

/// @dev BN254 curve parameters
contract EVMSTARKVerifier {
    /// @dev BN254 prime field modulus
    uint256 constant BN254_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev Grumpkin curve parameter (a = -17)
    uint256 constant GRUMPKIN_A = 21888242871839275222246405745257275088696311157297823662689037894645226208566;

    // ============================================
    // Verification Key (set at deployment)
    // ============================================

    /// @notice Alpha parameter (G1 generator scalar)
    uint256 public alphaX;
    uint256 public alphaY;

    /// @notice Beta parameter (G1 point)
    uint256 public betaX;
    uint256 public betaY;

    /// @notice Gamma parameter (G2 generator point)
    uint256 public gammaX1;
    uint256 public gammaX2;
    uint256 public gammaY1;
    uint256 public gammaY2;

    /// @notice Delta parameter (G2 point)
    uint256 public deltaX1;
    uint256 public deltaX2;
    uint256 public deltaY1;
    uint256 public deltaY2;

    /// @notice IC points for public input accumulation
    uint256[] public icX;
    uint256[] public icY;

    // ============================================
    // Proof Data
    // ============================================

    /// @notice Proof structure for Circle STARK IVC
    struct IVCProof {
        // Groth16 proof elements
        uint256[2] a;        // G1 point (A)
        uint256[2][2] b;     // G2 point (B) - [[x1, x0], [y1, y0]]
        uint256[2] c;        // G1 point (C)
        // IVC state
        uint256 accumulatedRoot;
        uint256 proofChainHash;
        uint256 stepCount;
    }

    /// @notice CycleFold deferred proof data
    struct CycleFoldProof {
        // Grumpkin accumulator
        uint256 accX;
        uint256 accY;
        uint256 u;
        // BN254 final check
        uint256 pairingInput0;
        uint256 pairingInput1;
    }

    // ============================================
    // Events
    // ============================================

    event ProofVerified(
        uint256 indexed blockNumber,
        uint256 stepCount,
        bool success
    );

    event VerificationFailed(
        string reason,
        uint256 stepCount
    );

    // ============================================
    // Constructor
    // ============================================

    /// @notice Deploy the verifier with verification key
    /// @param _alphaX Alpha G1 x coordinate
    /// @param _alphaY Alpha G1 y coordinate
    /// @param _betaX Beta G1 x coordinate
    /// @param _betaY Beta G1 y coordinate
    /// @param _gammaX1 Gamma G2 x (real part)
    /// @param _gammaX2 Gamma G2 x (imaginary part)
    /// @param _gammaY1 Gamma G2 y (real part)
    /// @param _gammaY2 Gamma G2 y (imaginary part)
    /// @param _deltaX1 Delta G2 x (real part)
    /// @param _deltaX2 Delta G2 x (imaginary part)
    /// @param _deltaY1 Delta G2 y (real part)
    /// @param _deltaY2 Delta G2 y (imaginary part)
    /// @param _icX Array of IC point x coordinates
    /// @param _icY Array of IC point y coordinates
    constructor(
        uint256 _alphaX,
        uint256 _alphaY,
        uint256 _betaX,
        uint256 _betaY,
        uint256 _gammaX1,
        uint256 _gammaX2,
        uint256 _gammaY1,
        uint256 _gammaY2,
        uint256 _deltaX1,
        uint256 _deltaX2,
        uint256 _deltaY1,
        uint256 _deltaY2,
        uint256[] memory _icX,
        uint256[] memory _icY
    ) {
        alphaX = _alphaX;
        alphaY = _alphaY;
        betaX = _betaX;
        betaY = _betaY;
        gammaX1 = _gammaX1;
        gammaX2 = _gammaX2;
        gammaY1 = _gammaY1;
        gammaY2 = _gammaY2;
        deltaX1 = _deltaX1;
        deltaX2 = _deltaX2;
        deltaY1 = _deltaY1;
        deltaY2 = _deltaY2;
        icX = _icX;
        icY = _icY;
    }

    // ============================================
    // Main Verification Functions
    // ============================================

    /// @notice Verify an IVC proof with CycleFold finalization
    /// @param _a G1 point A
    /// @param _b G2 point B
    /// @param _c G1 point C
    /// @param _publicInputs Public inputs array [accumulatedRoot, proofChainHash, stepCount, ...]
    /// @param _cycleFoldProof CycleFold deferred proof data
    /// @return True if verification succeeds
    function verifyIVCProof(
        uint256[2] memory _a,
        uint256[2][2] memory _b,
        uint256[2] memory _c,
        uint256[] memory _publicInputs,
        uint256[3] memory _cycleFoldProof
    ) public returns (bool) {
        // Grumpkin accumulator check (inlined)
        if (!(_cycleFoldProof[0] == 0 && _cycleFoldProof[1] == 0)) {
            uint256 grumpkinY2 = mulmod(_cycleFoldProof[1], _cycleFoldProof[1], BN254_Q);
            uint256 grumpkinX2 = mulmod(_cycleFoldProof[0], _cycleFoldProof[0], BN254_Q);
            uint256 grumpkinX3 = mulmod(grumpkinX2, _cycleFoldProof[0], BN254_Q);
            unchecked {
                uint256 rhs = (grumpkinX3 >= 17) ? grumpkinX3 - 17 : BN254_Q - (17 - grumpkinX3);
                if (grumpkinY2 != rhs) {
                    emit VerificationFailed("Grumpkin accumulator invalid", _publicInputs[2]);
                    return false;
                }
            }
        }

        // Compute vk_x and verify pairing
        uint256[2] memory vk_x = computePublicInputAccumulation(_publicInputs);
        bool pairingValid = verifyPairing(_a, _b, _c, vk_x);

        if (pairingValid) {
            emit ProofVerified(_publicInputs[0], _publicInputs[2], true);
        } else {
            emit VerificationFailed("Pairing check failed", _publicInputs[2]);
        }

        return pairingValid;
    }

    /// @notice Verify multiple IVC proofs in batch
    /// @param _a Array of G1 points A
    /// @param _b Array of G2 points B
    /// @param _c Array of G1 points C
    /// @param _publicInputs Array of public inputs arrays
    /// @param _cycleFoldProofs Array of CycleFold proofs
    /// @return Array of verification results
    function verifyBatch(
        uint256[2][] memory _a,
        uint256[2][2][] memory _b,
        uint256[2][] memory _c,
        uint256[][] memory _publicInputs,
        uint256[3][] memory _cycleFoldProofs
    ) public view returns (bool[] memory) {
        uint256 len = _a.length;
        require(len == _b.length && len == _c.length && len == _publicInputs.length && len == _cycleFoldProofs.length, "Proof count mismatch");

        bool[] memory results = new bool[](len);
        for (uint256 i = 0; i < len; i++) {
            results[i] = verifyIVCProof(_a[i], _b[i], _c[i], _publicInputs[i], _cycleFoldProofs[i]);
        }

        return results;
    }

    // ============================================
    // Internal Helper Functions
    // ============================================

    /// @notice Compute vk_x = IC[0] + sum(publicInputs[i] * IC[i+1])
    /// @param _publicInputs Public inputs array
    /// @return vk_x Accumulated public input point
    function computePublicInputAccumulation(uint256[] memory _publicInputs)
        internal view
        returns (uint256[2] memory vk_x)
    {
        vk_x = [icX[0], icY[0]];

        uint256 len = _publicInputs.length;
        for (uint256 i = 0; i < len; ) {
            // Scalar multiplication: IC[i+1] * input[i]
            uint256[3] memory mulInput;
            mulInput[0] = icX[i + 1];
            mulInput[1] = icY[i + 1];
            mulInput[2] = _publicInputs[i];

            uint256[2] memory mulResult;
            assembly {
                let success := staticcall(gas(), 0x07, mulInput, 0x60, mulResult, 0x40)
                if iszero(success) { revert(0, 0) }
            }

            // Point addition: vk_x = vk_x + mulResult
            uint256[4] memory addInput;
            addInput[0] = vk_x[0];
            addInput[1] = vk_x[1];
            addInput[2] = mulResult[0];
            addInput[3] = mulResult[1];

            assembly {
                let success := staticcall(gas(), 0x06, addInput, 0x80, vk_x, 0x40)
                if iszero(success) { revert(0, 0) }
            }

            unchecked { i++; }
        }
    }

    /// @notice Verify the BN254 pairing equation
    /// @dev e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
    /// @param _a G1 point A
    /// @param _b G2 point B
    /// @param _c G1 point C
    /// @param _vkX Accumulated public input point
    /// @return True if pairing check passes
    function verifyPairing(
        uint256[2] memory _a,
        uint256[2][2] memory _b,
        uint256[2] memory _c,
        uint256[2] memory _vkX
    ) internal view returns (bool) {
        uint256[24] memory input;

        // e(-A, B)
        input[0] = _a[0];
        input[1] = negate(_a[1]);  // Negate y for -A
        input[2] = _b[0][0];
        input[3] = _b[0][1];
        input[4] = _b[1][0];
        input[5] = _b[1][1];

        // e(alpha, beta)
        input[6] = alphaX;
        input[7] = alphaY;
        input[8] = betaX;
        input[9] = betaY;

        // e(vk_x, gamma)
        input[10] = _vkX[0];
        input[11] = _vkX[1];
        input[12] = gammaX2;
        input[13] = gammaX1;
        input[14] = gammaY2;
        input[15] = gammaY1;

        // e(C, delta)
        input[16] = _c[0];
        input[17] = _c[1];
        input[18] = deltaX2;
        input[19] = deltaX1;
        input[20] = deltaY2;
        input[21] = deltaY1;

        uint256[1] memory result;
        assembly {
            let success := staticcall(
                gas(),
                0x08,          // ecPairing precompile
                input,
                0x300,         // 24 * 32 = 768 bytes
                result,
                0x20
            )
            if iszero(success) { revert(0, 0) }
        }

        return result[0] == 1;
    }

    /// @notice Verify Grumpkin curve accumulator
    /// @dev Checks y^2 = x^3 - 17 on Grumpkin
    /// @param _x X coordinate
    /// @param _y Y coordinate
    /// @return True if point is on Grumpkin curve
    function verifyGrumpkinAccumulator(uint256 _x, uint256 _y)
        internal pure
        returns (bool)
    {
        if (_x == 0 && _y == 0) {
            return true;  // Identity point is valid
        }

        // y^2 mod Q
        uint256 y2 = mulmod(_y, _y, BN254_Q);

        // x^3 mod Q
        uint256 x2 = mulmod(_x, _x, BN254_Q);
        uint256 x3 = mulmod(x2, _x, BN254_Q);

        // x^3 - 17 mod Q
        uint256 rhs;
        unchecked {
            if (x3 >= 17) {
                rhs = x3 - 17;
            } else {
                rhs = BN254_Q - (17 - x3);
            }
        }

        return y2 == rhs;
    }

    /// @notice Negate a field element
    /// @dev -y = Q - y (mod Q)
    /// @param _y Field element to negate
    /// @return Negated field element
    function negate(uint256 _y) internal pure returns (uint256) {
        if (_y == 0) return 0;
        return BN254_Q - _y;
    }

    // ============================================
    // View Functions (for off-chain queries)
    // ============================================

    /// @notice Get the number of public inputs
    function getNumPublicInputs() public view returns (uint256) {
        return icX.length - 1;
    }

    /// @notice Get verification key summary
    function getVKInfo() public view returns (
        uint256 _alphaX,
        uint256 _alphaY,
        uint256 _betaX,
        uint256 _betaY,
        uint256 _numIC
    ) {
        return (alphaX, alphaY, betaX, betaY, icX.length);
    }

    /// @notice Estimate verification gas cost
    function estimateVerificationGas(uint256 numPublicInputs)
        public pure
        returns (uint256)
    {
        // Base pairing cost: ~300k gas
        uint256 base = 300000;

        // Public input accumulation: ~50k per input
        uint256 perInput = 50000;

        // Grumpkin check: ~20k gas
        uint256 grumpkinCheck = 20000;

        return base + (numPublicInputs * perInput) + grumpkinCheck;
    }
}
